PACKAGE_NAME="pm80xx"
# from DRV_VERSION in pm8001_sas.h
PACKAGE_VERSION="0.1.40"
BUILT_MODULE_NAME[0]="pm80xx"
DEST_MODULE_LOCATION[0]="/kernel/drivers/scsi/pm8001"
MAKE[0]="make KVER=${kernelver} KDIR=${kernel_source_dir} modules"
CLEAN="make KVER=${kernelver} KDIR=${kernel_source_dir} clean"
POST_INSTALL="firmware-install.sh"
AUTOINSTALL="yes"

